name: Periodic update and publish

on:
  # see https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

  schedule:
    # Every first day of the month at 00:00 UTC
    - cron: "0 0 1 * *"

jobs:
  update-and-deploy:
    name: Update and deploy
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install

      # see https://playwright.dev/docs/ci-intro
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # publish can only add a commit if git user infos are set
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update and publish
        run: yarn run ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
